import { workflow } from "./helpers.js";

/**
 * Ported from runtime/graph/workflows/operations-trust.ts. All eight are grantable-domain
 * (domain.operations / domain.trust) and appear in catalog/bridge.ts's toCatalogInput().
 *
 * protectedCategory assignment follows the KTD4 rule verbatim: spend/release/destructive
 * actionClass nodes get the matching protectedCategory automatically; credentials_access,
 * legal_pricing, and public_actions tag a mutate/publish node only when its
 * founderOnlyActions text actually names that resource (not every founder-gated node gets
 * a protected-category tag — most are gated purely through the approvals mechanism).
 */
export const workflows = [
  workflow({
    id: "workflow.operations.paid-tool-routing-and-fallback",
    title: "Paid-tool routing & fallback",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before using or replacing any paid/account-gated tool, or before a free fallback",
    instructions:
      "Before using, skipping, or replacing any paid/account-gated tool (AppKittie, XPOZ, Firecrawl, Higgsfield, MobAI, Retention Mechanics), run ToolSearch for the tool's `mcp__<TOOLNAME>__` prefix and check for founder-supplied exports before concluding it is unavailable — a missing connector is not proof the founder lacks the tool. Present the three-choice Confirmation Prompt (use/provision, export/fallback, defer) through AskUserQuestion rather than a free-text blocker, and record the decision in `strategy/TOOL_DECISIONS.md` with tool, lane, access status, selected route, and fallback limitation. Treat MobAI's free tier (single device, Testing Mode) as needing no spend gate at all — only an upgrade or trial does. Never present a fallback artifact as equivalent to the paid-tool output; label it with confidence and the limitation, and route any credit/subscription spend through a separate protected ceiling, never inferred from the fallback choice.",
    reads: ["strategy/TOOL_DECISIONS.md", "state/PROJECT_STATE.yaml"],
    roleId: "role.operator-readiness",
    laneIds: ["paid_tool_routing"],
    phaseIds: ["phase.0b"],
    outputPaths: ["strategy/TOOL_DECISIONS.md"],
    providers: ["provider.doppler"],
    founderOnlyActions: ["approve a paid or constrained fallback"],
    actionClass: "mutate",
    idempotent: true,
  }),
  workflow({
    id: "workflow.operations.secrets-baseline-and-routing",
    title: "Secrets baseline & routing",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before any new secret, key, token, env var, webhook secret, or .env",
    instructions:
      "Before any new secret, API key, token, webhook signing secret, or `.env` value is introduced, classify it (public_client_config, server_secret, webhook_signing_secret, store_credential, oauth_or_refresh_token, ci_deploy_secret, runtime_user_secret, or local_operator_secret) and route it into Doppler by default — the business's own project for business-specific credentials, the shared `formation` project for account-level ones — recording only the name, class, and location in `trust/secrets/SECRETS.md`, never the value. Resolve the Doppler config name from `SECRETS.md` or `doppler configs --project <name>` before constructing any `doppler run` command; never guess between naming conventions like `prod` and `prd`. Set automation-consumed secrets with `masked` (not `restricted`) visibility so `doppler run --` can inject them, and never `source` an `.env`/`.p8` file — extract single values with `awk -F= '/^KEY=/{print $2}' file`. `check:secrets` fails the lane if a raw secret value appears in git, docs, screenshots, or logs, or if production uses a personal CLI token instead of a service token or OIDC.",
    reads: ["trust/secrets/SECRETS.md", "strategy/TOOL_DECISIONS.md", "state/PROJECT_STATE.yaml"],
    roleId: "role.engineering-leader",
    laneIds: ["secrets"],
    phaseIds: ["phase.0c"],
    outputPaths: ["trust/secrets/SECRETS.md"],
    gates: ["check:secrets"],
    providers: ["provider.doppler"],
    founderOnlyActions: ["provide or authorize credentials"],
    actionClass: "mutate",
    protectedCategory: "credentials_access",
    idempotent: true,
  }),
  workflow({
    id: "workflow.trust.security-architecture-and-release-gate",
    title: "Security architecture & release gate",
    domainId: "domain.trust",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before threat modeling, hardening, scans, or any security-readiness claim",
    instructions:
      "Create or refresh `trust/SECURITY.md` early enough (phase 1g) to shape `engineering/TECH_SPEC.md`, `trust/PRIVACY.md`, and `revenue/REVENUE_OPS.md`, then re-verify it as the release gate (phase 5c) before beta/TestFlight/store submission. Cover every required section — threat model, mobile hardening (Keychain/ATS/App Attest for iOS, Keystore/Network Security Config/Play Integrity for Android), backend/API controls, and revenue/entitlement abuse (RevenueCat/Stripe webhook signature verification, restore-purchases testing) — and mark platforms not in scope explicitly rather than omitting the section. Security is proven with evidence, not prose: attach scanner/review results or a founder-approved blocked route from `strategy/TOOL_DECISIONS.md` for each paid security tool (Claude Security, Codex Security, MobSF, Snyk/Semgrep) before claiming a section done. `npm run check:security` verifies the SECURITY.md contract shape, not vulnerabilities — pair it with an actual scan or review, and get founder sign-off on any accepted residual risk with an owner and revisit date.",
    reads: ["trust/SECURITY.md", "engineering/TECH_SPEC.md", "strategy/TOOL_DECISIONS.md"],
    // PRIVACY.md and REVENUE_OPS.md land at phase 3/3b, after this node's phase-1g threat-model
    // firing — consults, so the early half is not held hostage to later lanes; the 5c release
    // gate still cross-checks them via check:security once they exist.
    consults: ["trust/PRIVACY.md", "revenue/REVENUE_OPS.md"],
    roleId: "role.security-architect",
    laneIds: ["security"],
    phaseIds: ["phase.1g", "phase.5c"],
    outputPaths: ["trust/SECURITY.md", "trust/security-review.html"],
    gates: ["check:security"],
    providers: ["provider.security-review", "provider.sentry"],
    founderOnlyActions: ["accept residual security risk"],
    actionClass: "mutate",
    idempotent: true,
  }),
  workflow({
    id: "workflow.trust.privacy-and-terms",
    title: "Privacy & terms",
    domainId: "domain.trust",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before privacy policy, terms, EULA, subscription terms, account-deletion, store disclosures",
    instructions:
      "Build the data inventory before drafting any policy text — trace actual data flows from `state/LAUNCH_TRACE.md` and `engineering/TECH_SPEC.md` (accounts, user content, device permissions, analytics/ads vendors, payments, AI processing) rather than starting from a template. Draft `trust/PRIVACY.md` and `trust/TERMS.md` to match actual practice — Apple's App Privacy answers and Google Play Data safety must match the same inventory — and publish stable `/privacy`, `/terms`, and `/delete-account` pages that return HTTP 200 and are linked from settings, App Store Connect, and Play Console. Produce `LEGAL_REVIEW.md` with sources checked, the data inventory table, store-disclosure mapping, and an explicit founder/counsel approval checkbox; never mark legal pages final without that approval. Verify contact-email MX records with `dig MX yourdomain.com +short` before writing any `@yourdomain.com` address into published copy — an unverified address that never receives mail is a store-policy and reputation risk.",
    reads: ["state/LAUNCH_TRACE.md", "engineering/TECH_SPEC.md"],
    roleId: "role.customer-success",
    laneIds: ["privacy_legal"],
    phaseIds: ["phase.3"],
    dependencies: ["workflow.process.launch-trace-and-build-contracts"],
    outputPaths: ["trust/PRIVACY.md", "trust/TERMS.md", "LEGAL_REVIEW.md"],
    founderOnlyActions: ["approve legal text"],
    actionClass: "publish",
    protectedCategory: "legal_pricing",
    idempotent: true,
  }),
  workflow({
    id: "workflow.operations.resend-email-ops",
    title: "Resend email ops",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before Resend domains/keys, transactional/lifecycle/broadcast email, deliverability",
    instructions:
      "Set up Resend with a purpose-specific sending subdomain (never the apex domain), add SPF/DKIM, then DMARC starting at `p=none` before tightening — verify all three pass on a real test send before any production email goes out. Classify every email as transactional, lifecycle, marketing/broadcast, or inbound/support; trigger lifecycle Automations from events that already exist in `analytics/ANALYTICS.md`, and adapt the starter pack at `growth/resend/email-templates.ts` with brand tokens pulled from `design/design.md` into `LaunchEmailBrand.designSystem` and tone from `11_STAR_EXPERIENCE.md` — do not ship generic-looking email. Verify webhooks against the raw request body and store processed `svix-id` values, since Resend webhooks are at-least-once and may duplicate. Every subject/preview/body must pass the `no-slop-writing.md` self-check in the product's brand voice, and `check:email` gates production sends on a verified domain, server-only API keys, and unsubscribe handling on every non-transactional message.",
    reads: ["design/design.md", "analytics/ANALYTICS.md", "product/experience/11-star-experience/11_STAR_EXPERIENCE.md", "growth/resend/email-templates.ts"],
    // customer-success over marketing-guru: the roster scopes "lifecycle copy" and the monitored
    // inbox to customer success; the DNS/webhook setup half follows the runbook either way.
    roleId: "role.customer-success",
    laneIds: ["email"],
    phaseIds: ["phase.4", "phase.6"],
    dependencies: ["workflow.design.design-room-state-mutate-version-render", "workflow.data.analytics-and-attribution-blueprint"],
    outputPaths: ["growth/EMAIL_OPS.md"],
    gates: ["check:email"],
    providers: ["provider.resend"],
    actionClass: "publish",
    // Production sends and DNS changes are public actions: the category is the authorization
    // control (grants/waivers), independent of check:email's after-the-fact verification.
    protectedCategory: "public_actions",
    idempotent: false,
  }),
  workflow({
    id: "workflow.operations.post-launch-operations",
    title: "Post-launch operations",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: 'App live (phase_6/6b), "what now", weekly ops, incident response, retention reviews',
    instructions:
      "Run the named Weekly Ops Review in fixed order — metrics pull (PostHog/RevenueCat/console numbers, not adjectives), crash/review triage, support sweep, ASO delta, growth/spend review against `growth/PAID_UA.md`'s stop/scale rules, then ship one user-visible improvement — and log a one-line delta per step in `operations/POST_LAUNCH_OPS.md` dated against `lanes.post_launch_ops.live_since`. Route involuntary billing churn through the recovery levers, not written off as normal, and when retention cohorts show a consistent drop at one step, open it through `change-cascade.md` rather than patching only the surface that failed. At the day-30 and day-90 checkpoints, prepare the Kill/Hold/Fix/Scale evidence pack (MRR trajectory, D7/D30 retention trend, CAC/LTV payback, founder hours) in `operations/LAUNCH_RETRO.md` — the agent assembles evidence, the founder makes the verdict. `check:post-launch` fails a checkpoint left uncompleted past its due date or a metric cell holding a placeholder instead of a number.",
    reads: ["state/PROJECT_STATE.yaml", "operations/POST_LAUNCH_OPS.md", "operations/LAUNCH_RETRO.md"],
    // PAID_UA.md's producer is the spend node, which parks until the founder funds it — a launch
    // that never buys ads still runs post-launch operations, so this is a consult.
    consults: ["growth/PAID_UA.md"],
    roleId: "role.orchestrator",
    laneIds: ["post_launch_ops"],
    phaseIds: ["phase.6b"],
    dependencies: ["workflow.engineering.engineering-orchestration-ce-production-readiness"],
    outputPaths: ["operations/POST_LAUNCH_OPS.md", "operations/LAUNCH_RETRO.md"],
    gates: ["check:post-launch"],
    founderOnlyActions: ["decide Kill, Hold, Fix, or Scale"],
    actionClass: "mutate",
    idempotent: true,
  }),
  workflow({
    id: "workflow.operations.founder-zero-operator-bootstrap",
    title: "Founder-zero operator bootstrap",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Every broad launch start; before account/social/Doppler bootstrap; when an agent is about to hand back a checklist",
    instructions:
      "At the start of every broad launch, offer one recommended step-away setup before build work. In that exchange, settle autonomy and budget, confirm business identity and founder-owned recovery/2FA, verify Doppler or the approved secret manager, inventory every in-scope account and tool, confirm durable operator roles, and record the requested exact deployment, signing, App Store Connect, Google Play, asset, screenshot, and test-upload authority in operations/business-access.json. The following agent-operations node verifies those capabilities and materializes separate standing envelopes for the named website deploy, asset generation inside the ceiling, approved store metadata/media, and TestFlight or Play testing-track uploads. Keep exactly one structured `activeFounderGate`, and set it to `null` while the agent can work. Combine missing tools and roles into one founder handoff. Never request a password, 2FA code, recovery code, or session token in chat. Consume matching standing envelopes without another prompt, read back each result, and continue. Pause later only for missing or expired scope, a ceiling overrun, protected identity/legal/pricing/credential changes, destruction, or a final public release not approved in the opening envelope.",
    reads: ["operations/BUSINESS_ACCESS.md", "operations/business-access.json", "state/PROJECT_STATE.yaml"],
    roleId: "role.operator-readiness",
    outputPaths: ["operations/BUSINESS_ACCESS.md", "operations/business-access.json"],
    gates: ["check:founder-operator"],
    founderOnlyActions: ["approve the consolidated step-away authority and complete unavoidable ownership authentication"],
    actionClass: "mutate",
    protectedCategory: "credentials_access",
    idempotent: true,
  }),
  workflow({
    id: "workflow.operations.agent-operations-ledger",
    title: "Agent operations ledger",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before any authenticated browser/API/CLI/native action on a provider, social, or store account",
    instructions:
      "Before build work starts, derive the required capability list from launch scope and inspect connectors, APIs/CLIs, authenticated browser access, devices, source control, CI, hosting/DNS, asset generation, screenshots, signing, App Store Connect, Google Play, analytics, revenue, email, and support as applicable. Record exact accounts, projects/apps, environments, modes, checked times, and durable operator roles in `operations/agent-operations.json`. Create separate standing envelopes for website deployment, asset work, approved store metadata/media, and TestFlight or Play testing-track uploads. For each later action, classify it as observe/draft/mutate/publish/spend/release/destructive and bind it to a matching current envelope. Consume a matching standing envelope automatically; never ask twice. Select the narrowest route, capture sanitized before-state, act, read back provider state, and reconcile proof. Combine missing capabilities or authority into one handoff while other work continues. Sticky identity/legal fields — app name, bundle ID, seller identity, banking/tax, pricing, credential roles — and any unapproved final public release remain exceptional gates. Run `npm run check:agent-operations` before an unattended-readiness or authenticated-operation claim.",
    reads: ["operations/AGENT_OPERATIONS.md", "operations/agent-operations.json", "operations/PROVIDER_PROOF.md", "state/PROJECT_STATE.yaml"],
    roleId: "role.operator-readiness",
    dependencies: [
      "workflow.operations.founder-zero-operator-bootstrap",
      "workflow.operations.paid-tool-routing-and-fallback",
      "workflow.operations.secrets-baseline-and-routing",
    ],
    outputPaths: ["operations/AGENT_OPERATIONS.md", "operations/agent-operations.json"],
    gates: ["check:agent-operations"],
    providers: [
      "provider.doppler",
      "provider.app-store-connect",
      "provider.google-play",
      "provider.posthog",
      "provider.revenuecat",
      "provider.stripe",
      "provider.resend",
      "provider.app-store-screenshots",
      "provider.higgsfield",
      "provider.mobai",
      "provider.in-app-ios-simulator",
      "provider.codex-native-ios",
      "provider.snapshot-previews",
      "provider.serve-sim",
      "provider.aso-skills",
      "provider.refero",
      "provider.security-review",
      "provider.sentry",
      "provider.paid-ad-channels",
    ],
    actionClass: "mutate",
    idempotent: true,
  }),
  workflow({
    id: "workflow.trust.community-and-user-safety",
    title: "Community and user safety",
    domainId: "domain.trust",
    areaIds: ["area.business-operations-trust"],
    trigger: "When the product includes social, chat, creator, or other user-generated content",
    instructions:
      "Confirm whether users can create, share, discover, or message content. When required, define moderation, reporting, blocking, escalation, support contact, age controls, response targets, and evidence. Record the operating model in trust/COMMUNITY_SAFETY.md. Test the common abuse and recovery paths. Do not mark this work as not needed without a reason and product evidence.",
    reads: ["product/SPEC.md", "trust/PRIVACY.md"],
    roleId: "role.security-architect",
    laneIds: ["security", "privacy_legal"],
    phaseIds: ["phase.3", "phase.5c"],
    dependencies: ["workflow.research.research-backed-spec"],
    outputPaths: ["trust/COMMUNITY_SAFETY.md"],
    actionClass: "mutate",
    idempotent: true,
    applicability: {
      mode: "conditional",
      question: "Does the product include social, chat, creator, or other user-generated content?",
    },
  }),
  workflow({
    id: "workflow.trust.generative-ai-safety",
    title: "Generative-AI safety",
    domainId: "domain.trust",
    areaIds: ["area.business-operations-trust"],
    trigger: "When the product generates text, images, audio, or video",
    instructions:
      "Confirm whether the product generates text, images, audio, or video. When required, define prohibited uses, input and output controls, reporting, enforcement, human escalation, age controls, and model or provider responsibilities. Test harmful, deceptive, exploitative, and sexual-content abuse cases. Record controls and evidence in trust/AI_SAFETY.md. Do not mark this work as not needed without a reason and product evidence.",
    reads: ["product/SPEC.md", "trust/SECURITY.md", "trust/PRIVACY.md"],
    roleId: "role.security-architect",
    laneIds: ["security", "privacy_legal"],
    phaseIds: ["phase.3", "phase.5c"],
    dependencies: ["workflow.research.research-backed-spec"],
    outputPaths: ["trust/AI_SAFETY.md"],
    actionClass: "mutate",
    idempotent: true,
    applicability: {
      mode: "conditional",
      question: "Does the product generate text, images, audio, or video?",
    },
  }),
] as const;
