import { workflow } from "./helpers.js";

/**
 * Ported from runtime/graph/workflows/operations-trust.ts. All eight are grantable-domain
 * (domain.operations / domain.trust) and appear in catalog/bridge.ts's toCatalogInput().
 *
 * protectedCategory assignment follows the KTD4 rule verbatim: spend/release/destructive
 * actionClass nodes get the matching protectedCategory automatically; credentials_access,
 * legal_pricing, and public_actions tag a mutate/publish node only when its
 * founderOnlyActions text actually names that resource (not every founder-gated node gets
 * a protected-category tag — most are gated purely through the approvals mechanism).
 */
export const workflows = [
  workflow({
    id: "workflow.operations.paid-tool-routing-and-fallback",
    title: "Paid-tool routing & fallback",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before using or replacing any paid/account-gated tool, or before a free fallback",
    laneIds: ["paid_tool_routing"],
    phaseIds: ["phase.0b"],
    outputPaths: ["strategy/TOOL_DECISIONS.md"],
    gates: ["check:paid-tool-decisions"],
    providers: ["provider.doppler"],
    founderOnlyActions: ["approve a paid or constrained fallback"],
    actionClass: "mutate",
    idempotent: true,
  }),
  workflow({
    id: "workflow.operations.secrets-baseline-and-routing",
    title: "Secrets baseline & routing",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before any new secret, key, token, env var, webhook secret, or .env",
    laneIds: ["secrets"],
    phaseIds: ["phase.0c"],
    outputPaths: ["trust/secrets/SECRETS.md"],
    gates: ["check:secrets"],
    providers: ["provider.doppler"],
    founderOnlyActions: ["provide or authorize credentials"],
    actionClass: "mutate",
    protectedCategory: "credentials_access",
    idempotent: true,
  }),
  workflow({
    id: "workflow.trust.security-architecture-and-release-gate",
    title: "Security architecture & release gate",
    domainId: "domain.trust",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before threat modeling, hardening, scans, or any security-readiness claim",
    laneIds: ["security"],
    phaseIds: ["phase.1g", "phase.5c"],
    outputPaths: ["trust/SECURITY.md", "trust/security-review.html"],
    gates: ["check:security"],
    providers: ["provider.security-review", "provider.sentry"],
    founderOnlyActions: ["accept residual security risk"],
    actionClass: "mutate",
    idempotent: true,
  }),
  workflow({
    id: "workflow.trust.privacy-and-terms",
    title: "Privacy & terms",
    domainId: "domain.trust",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before privacy policy, terms, EULA, subscription terms, account-deletion, store disclosures",
    laneIds: ["privacy_legal"],
    phaseIds: ["phase.3"],
    dependencies: ["workflow.process.launch-trace-and-build-contracts"],
    outputPaths: ["trust/PRIVACY.md", "trust/TERMS.md", "LEGAL_REVIEW.md"],
    gates: ["check:privacy-terms"],
    founderOnlyActions: ["approve legal text"],
    actionClass: "publish",
    protectedCategory: "legal_pricing",
    idempotent: true,
  }),
  workflow({
    id: "workflow.operations.resend-email-ops",
    title: "Resend email ops",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before Resend domains/keys, transactional/lifecycle/broadcast email, deliverability",
    laneIds: ["email"],
    phaseIds: ["phase.4", "phase.6"],
    dependencies: ["workflow.design.design-room-state-mutate-version-render", "workflow.data.analytics-and-attribution-blueprint"],
    outputPaths: ["growth/EMAIL_OPS.md"],
    gates: ["check:email"],
    providers: ["provider.resend"],
    actionClass: "publish",
    idempotent: false,
  }),
  workflow({
    id: "workflow.operations.post-launch-operations",
    title: "Post-launch operations",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: 'App live (phase_6/6b), "what now", weekly ops, incident response, retention reviews',
    laneIds: ["post_launch_ops"],
    phaseIds: ["phase.6b"],
    dependencies: ["workflow.engineering.engineering-orchestration-ce-production-readiness"],
    outputPaths: ["operations/POST_LAUNCH_OPS.md", "operations/LAUNCH_RETRO.md"],
    gates: ["check:post-launch"],
    founderOnlyActions: ["decide Kill, Hold, Fix, or Scale"],
    actionClass: "mutate",
    idempotent: true,
  }),
  workflow({
    id: "workflow.operations.founder-zero-operator-bootstrap",
    title: "Founder-zero operator bootstrap",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Every broad launch start; before account/social/Doppler bootstrap; when an agent is about to hand back a checklist",
    outputPaths: ["operations/BUSINESS_ACCESS.md", "operations/business-access.json"],
    gates: ["check:founder-operator"],
    founderOnlyActions: ["provide account ownership decisions"],
    actionClass: "mutate",
    protectedCategory: "credentials_access",
    idempotent: true,
  }),
  workflow({
    id: "workflow.operations.agent-operations-ledger",
    title: "Agent operations ledger",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before any authenticated browser/API/CLI/native action on a provider, social, or store account",
    outputPaths: ["operations/AGENT_OPERATIONS.md", "operations/agent-operations.json"],
    gates: ["check:agent-operations"],
    providers: ["provider.app-store-connect", "provider.google-play", "provider.posthog", "provider.revenuecat"],
    founderOnlyActions: ["approve exact authenticated actions"],
    actionClass: "mutate",
    protectedCategory: "credentials_access",
    idempotent: true,
  }),
] as const;
