#!/usr/bin/env node
/**
 * install-schedule.ts — writes (or removes) an OS-level schedule that invokes a business
 * workspace's scheduled session (KTD1: OS cron/launchd as the trigger, vendor schedulers as
 * interchangeable alternates). Mirrors tooling/install-hooks.ts's CLI shape and safety posture:
 * DEFAULT IS --dry-run (prints what would be installed, touches nothing); --apply is required to
 * touch the real system (crontab / launchctl). --apply is never invoked from this session or from
 * any fixture — verification/fixtures/adapters.fixtures.ts asserts generated content only, via the
 * pure render/apply functions below, never against the real crontab or a real LaunchAgents file.
 *
 * Usage:
 *   tsx core/adapters/install-schedule.ts --workspace <dir> --runtime claude|codex|cursor \
 *       --schedule "(every 30 min, 5-field cron)" --brief <path/to/brief.json> [--mechanism cron|launchd] \
 *       [--wall-clock-seconds 1800] [--skill-root <path>] [--apply] [--uninstall]
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import os from "node:os";
import { spawnSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";
import { expandHome, flagBoolean, flagNumber, flagString, parseFlags } from "../../tooling/lib/launch-state.js";
import { isMainModule } from "../lib/cli.js";
import { founderFacingRuntimeIds, type RuntimeId } from "./profile.js";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const defaultSkillRoot = path.resolve(scriptDir, "..", "..");

export type ScheduleMechanism = "cron" | "launchd";

export interface ScheduleOptions {
  readonly workspaceDir: string;
  readonly runtime: RuntimeId;
  readonly schedule: string;
  readonly briefPath: string;
  readonly wallClockSeconds: number;
  readonly skillRoot: string;
  readonly wrapperPath: string;
  readonly logPath: string;
  readonly workspaceSlug: string;
}

// --- pure rendering (fixture-safe: no filesystem, no subprocess) ----------------------------

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

/** file:// import specifier a generated .mts wrapper uses to reach this skill's adapter modules from inside a business workspace. */
function importSpecifier(skillRoot: string, relativeModulePath: string): string {
  return pathToFileURL(path.join(skillRoot, relativeModulePath)).href;
}

export function renderWrapperScript(options: ScheduleOptions): string {
  const profileImport = importSpecifier(options.skillRoot, `core/adapters/${options.runtime}.ts`);
  const sharedImport = importSpecifier(options.skillRoot, "core/adapters/profile.ts");
  const creatorName = `create${capitalize(options.runtime)}Profile`;
  return `#!/usr/bin/env -S tsx
// GENERATED by core/adapters/install-schedule.ts for workspace ${options.workspaceDir} / runtime ${options.runtime}.
// Do not edit by hand — reinstall (npm exec tsx core/adapters/install-schedule.ts ... --apply) to regenerate.
import { spawnSync } from "node:child_process";
import { ${creatorName} } from ${JSON.stringify(profileImport)};
import { wrapWithWallClock } from ${JSON.stringify(sharedImport)};

const sessionId = \`sched-\${new Date().toISOString().replace(/[:.]/g, "-")}\`;
const profile = ${creatorName}();
const headless = profile.buildHeadlessCommand({
  workspaceDir: ${JSON.stringify(options.workspaceDir)},
  briefPath: ${JSON.stringify(options.briefPath)},
  sessionId,
  wallClockSeconds: ${options.wallClockSeconds},
  maxConcurrency: profile.maxConcurrency,
});
const wrapped = wrapWithWallClock(headless, ${options.wallClockSeconds});
if (wrapped.enforcementGap) console.error(\`wall-clock: \${wrapped.enforcementGap}\`);
const result = spawnSync(wrapped.command, [...wrapped.args], { stdio: "inherit", cwd: ${JSON.stringify(options.skillRoot)} });
process.exit(result.status ?? 1);
`;
}

export function crontabSignature(options: Pick<ScheduleOptions, "workspaceSlug" | "runtime">): string {
  return `formation:${options.workspaceSlug}:${options.runtime}`;
}

/** Signature written by installs that predate the formation rename; still matched so those jobs stay removable. */
export function legacyCrontabSignature(options: Pick<ScheduleOptions, "workspaceSlug" | "runtime">): string {
  return `b2c-mobile-business-launch:${options.workspaceSlug}:${options.runtime}`;
}

export function renderCrontabLine(options: ScheduleOptions): string {
  return `${options.schedule} /usr/bin/env tsx ${options.wrapperPath} >> ${options.logPath} 2>&1 # ${crontabSignature(options)}`;
}

/** Removes only lines tagged with this workspace+runtime's signature; every other line (including a foreign crontab's own entries) is untouched. */
export function filterCrontabLines(existingLines: readonly string[], signature: string): string[] {
  return existingLines.filter((line) => !line.includes(`# ${signature}`));
}

export function applyCrontabInstall(existingContent: string, options: ScheduleOptions): { nextContent: string; line: string } {
  const lines = existingContent.split("\n").filter((line) => line.length > 0);
  const withoutOurs = filterCrontabLines(filterCrontabLines(lines, crontabSignature(options)), legacyCrontabSignature(options));
  const line = renderCrontabLine(options);
  return { nextContent: `${[...withoutOurs, line].join("\n")}\n`, line };
}

/** The exact reverse of applyCrontabInstall for the same options: removes our line, leaves everything else (order and all) untouched. */
export function applyCrontabUninstall(existingContent: string, options: ScheduleOptions): { nextContent: string; removed: string[] } {
  const signatures = [crontabSignature(options), legacyCrontabSignature(options)];
  const lines = existingContent.split("\n").filter((line) => line.length > 0);
  const removed = lines.filter((line) => signatures.some((signature) => line.includes(`# ${signature}`)));
  const kept = signatures.reduce((acc, signature) => filterCrontabLines(acc, signature), lines as string[]);
  return { nextContent: kept.length > 0 ? `${kept.join("\n")}\n` : "", removed };
}

export type CronToLaunchdTranslation = { kind: "interval"; seconds: number } | { kind: "calendar"; hour: number; minute: number } | { kind: "unsupported"; reason: string };

/**
 * launchd has no native cron-expression support. This translates the two common shapes a founder
 * or the onboarding console would actually produce ("every N minutes", "daily at H:M"); anything
 * else is reported as unsupported rather than silently approximated.
 */
export function translateCronToLaunchd(schedule: string): CronToLaunchdTranslation {
  const fields = schedule.trim().split(/\s+/);
  if (fields.length !== 5) return { kind: "unsupported", reason: `expected a 5-field cron expression, got "${schedule}"` };
  const [minute, hour, dom, month, dow] = fields as [string, string, string, string, string];
  if (dom === "*" && month === "*" && dow === "*") {
    const everyMinutes = /^\*\/(\d+)$/.exec(minute);
    if (everyMinutes && hour === "*") {
      const n = Number(everyMinutes[1]);
      if (n > 0) return { kind: "interval", seconds: n * 60 };
    }
    if (/^\d+$/.test(minute) && /^\d+$/.test(hour)) {
      return { kind: "calendar", hour: Number(hour), minute: Number(minute) };
    }
  }
  return { kind: "unsupported", reason: `launchd translation only supports "*/N * * * *" (every N minutes) or "M H * * *" (daily at H:M); got "${schedule}"` };
}

export function launchdLabel(options: Pick<ScheduleOptions, "workspaceSlug" | "runtime">): string {
  return `com.formation.${options.workspaceSlug}.${options.runtime}`;
}

export function launchdPlistPath(options: Pick<ScheduleOptions, "workspaceSlug" | "runtime">, homeDir = os.homedir()): string {
  return path.join(homeDir, "Library", "LaunchAgents", `${launchdLabel(options)}.plist`);
}

/** Label written by installs that predate the formation rename; still resolved so those jobs stay removable. */
export function legacyLaunchdLabel(options: Pick<ScheduleOptions, "workspaceSlug" | "runtime">): string {
  return `com.b2c-mobile-business-launch.${options.workspaceSlug}.${options.runtime}`;
}

export function legacyLaunchdPlistPath(options: Pick<ScheduleOptions, "workspaceSlug" | "runtime">, homeDir = os.homedir()): string {
  return path.join(homeDir, "Library", "LaunchAgents", `${legacyLaunchdLabel(options)}.plist`);
}

export type LaunchdPlistResult = { ok: true; xml: string } | { ok: false; error: string };

export function renderLaunchdPlist(options: ScheduleOptions): LaunchdPlistResult {
  const translated = translateCronToLaunchd(options.schedule);
  if (translated.kind === "unsupported") return { ok: false, error: translated.reason };
  const label = launchdLabel(options);
  const scheduleXml =
    translated.kind === "interval"
      ? `  <key>StartInterval</key>\n  <integer>${translated.seconds}</integer>\n`
      : `  <key>StartCalendarInterval</key>\n  <dict>\n    <key>Hour</key><integer>${translated.hour}</integer>\n    <key>Minute</key><integer>${translated.minute}</integer>\n  </dict>\n`;
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/env</string>
    <string>tsx</string>
    <string>${options.wrapperPath}</string>
  </array>
  <key>StandardOutPath</key><string>${options.logPath}</string>
  <key>StandardErrorPath</key><string>${options.logPath}</string>
${scheduleXml}  <key>RunAtLoad</key><false/>
</dict>
</plist>
`;
  return { ok: true, xml };
}

// --- CLI ---------------------------------------------------------------------------------------

function fail(message: string): never {
  console.error(`install-schedule: ${message}`);
  process.exit(1);
}

function buildOptions(argv: string[]): { options: ScheduleOptions; mechanism: ScheduleMechanism; apply: boolean; uninstall: boolean } {
  const flags = parseFlags(argv, [
    { flags: ["--workspace", "--target"], key: "workspace" },
    { flags: ["--runtime"], key: "runtime", kind: "string" },
    { flags: ["--schedule"], key: "schedule", kind: "string" },
    { flags: ["--brief"], key: "brief" },
    { flags: ["--mechanism"], key: "mechanism", kind: "string" },
    { flags: ["--wall-clock-seconds"], key: "wallClockSeconds", kind: "number" },
    { flags: ["--skill-root"], key: "skillRoot" },
    { flags: ["--log"], key: "log" },
    { flags: ["--apply"], key: "apply", kind: "boolean" },
    { flags: ["--uninstall"], key: "uninstall", kind: "boolean" },
  ]);

  const workspaceDir = flagString(flags, "workspace") ? path.resolve(expandHome(flagString(flags, "workspace")!)) : undefined;
  if (!workspaceDir) fail("--workspace <business-workspace-dir> is required.");
  const runtime = flagString(flags, "runtime") as RuntimeId | undefined;
  if (!runtime || !founderFacingRuntimeIds.includes(runtime)) fail(`--runtime ${founderFacingRuntimeIds.join("|")} is required (inline is a fixture-only shape, never scheduled).`);
  const schedule = flagString(flags, "schedule");
  if (!schedule) fail('--schedule "<5-field cron expression>" is required, e.g. "*/30 * * * *".');
  const briefPath = flagString(flags, "brief") ? path.resolve(expandHome(flagString(flags, "brief")!)) : path.join(workspaceDir!, "brief.json");
  const skillRoot = path.resolve(expandHome(flagString(flags, "skillRoot") ?? defaultSkillRoot));
  const wallClockSeconds = flagNumber(flags, "wallClockSeconds") ?? 1800;
  const workspaceSlug = path.basename(workspaceDir!);
  const scheduleDir = path.join(workspaceDir!, "schedule");
  const wrapperPath = path.join(scheduleDir, `run-${runtime}.mts`);
  const logPath = flagString(flags, "log") ? path.resolve(expandHome(flagString(flags, "log")!)) : path.join(scheduleDir, `run-${runtime}.log`);
  const mechanism = (flagString(flags, "mechanism") as ScheduleMechanism | undefined) ?? "cron";
  if (mechanism !== "cron" && mechanism !== "launchd") fail(`--mechanism must be "cron" or "launchd", got "${mechanism}".`);

  return {
    options: { workspaceDir: workspaceDir!, runtime, schedule, briefPath, wallClockSeconds, skillRoot, wrapperPath, logPath, workspaceSlug },
    mechanism,
    apply: flagBoolean(flags, "apply"),
    uninstall: flagBoolean(flags, "uninstall"),
  };
}

function readCrontab(): string {
  const result = spawnSync("crontab", ["-l"], { encoding: "utf8" });
  // An empty/never-configured crontab exits nonzero on most platforms — that's "no crontab yet", not an error.
  if (result.status !== 0) return "";
  return result.stdout ?? "";
}

function writeCrontab(content: string): void {
  const result = spawnSync("crontab", ["-"], { input: content, encoding: "utf8" });
  if (result.status !== 0) fail(`crontab install failed: ${result.stderr || result.stdout || `exit ${String(result.status)}`}`);
}

function runMain(): void {
  const { options, mechanism, apply, uninstall } = buildOptions(process.argv.slice(2));

  if (mechanism === "cron") {
    if (!apply) {
      console.log(`install-schedule: DRY RUN (${uninstall ? "uninstall" : "install"}, cron) — would write the wrapper script and update the user crontab.`);
      console.log(`  wrapper: ${options.wrapperPath}`);
      if (!uninstall) console.log(`  crontab line: ${renderCrontabLine(options)}`);
      console.log(`  would remove any crontab line tagged "# ${crontabSignature(options)}" or "# ${legacyCrontabSignature(options)}"`);
      console.log(`  verify after --apply with: crontab -l | grep ${JSON.stringify(crontabSignature(options))}`);
      return;
    }
    mkdirSync(path.dirname(options.wrapperPath), { recursive: true });
    const current = readCrontab();
    const result = uninstall ? applyCrontabUninstall(current, options) : applyCrontabInstall(current, options);
    if (!uninstall) writeFileSync(options.wrapperPath, renderWrapperScript(options), { mode: 0o755 });
    writeCrontab(result.nextContent);
    console.log(`install-schedule: ${uninstall ? "removed" : "installed"} the cron entry for ${options.workspaceSlug}/${options.runtime}.`);
    return;
  }

  // launchd
  const plist = renderLaunchdPlist(options);
  if (!plist.ok) fail(plist.error);
  const plistPath = launchdPlistPath(options);
  if (!apply) {
    console.log(`install-schedule: DRY RUN (${uninstall ? "uninstall" : "install"}, launchd) — would write the wrapper script and ${uninstall ? "unload + remove" : "write + load"} the LaunchAgent plist.`);
    console.log(`  wrapper: ${options.wrapperPath}`);
    console.log(`  plist:   ${plistPath}`);
    console.log(`  would also unload + remove the legacy plist when present: ${legacyLaunchdPlistPath(options)}`);
    if (!uninstall) console.log(plist.xml);
    return;
  }
  const legacyPlistPath = legacyLaunchdPlistPath(options);
  if (uninstall) {
    for (const target of [plistPath, legacyPlistPath]) {
      if (existsSync(target)) {
        spawnSync("launchctl", ["unload", target], { encoding: "utf8" });
        spawnSync("rm", ["-f", target], { encoding: "utf8" });
      }
    }
    console.log(`install-schedule: removed the launchd job for ${options.workspaceSlug}/${options.runtime}.`);
    return;
  }
  if (existsSync(legacyPlistPath)) {
    spawnSync("launchctl", ["unload", legacyPlistPath], { encoding: "utf8" });
    spawnSync("rm", ["-f", legacyPlistPath], { encoding: "utf8" });
  }
  mkdirSync(path.dirname(options.wrapperPath), { recursive: true });
  writeFileSync(options.wrapperPath, renderWrapperScript(options), { mode: 0o755 });
  mkdirSync(path.dirname(plistPath), { recursive: true });
  writeFileSync(plistPath, plist.xml);
  spawnSync("launchctl", ["load", plistPath], { encoding: "utf8" });
  console.log(`install-schedule: installed the launchd job for ${options.workspaceSlug}/${options.runtime}.`);
}

if (isMainModule(import.meta.url)) {
  runMain();
}
