import type { CatalogPhase } from "./types.js";

/** Ported unchanged from runtime/graph/phases.ts (U8). Feeds catalog/render-routing.ts's spine.md. */
export const phases: readonly CatalogPhase[] = [
  {
    id: "phase.0-orient",
    key: "phase_0_orient",
    label: "0",
    focus: "Founder-zero orient and scaffold",
    primaryOutput: "operations/BUSINESS_ACCESS.md + ledger, state/PROJECT_STATE.yaml, autonomy/scope, first cockpit",
    order: 0,
    orientWindow: true,
  },
  {
    id: "phase.0a",
    key: "phase_0a",
    label: "0a",
    focus: "Access and account orientation",
    primaryOutput: "Business identity, account inventory, and one-next-action handoff",
    order: 1,
    orientWindow: true,
  },
  {
    id: "phase.0b",
    key: "phase_0b",
    label: "0b",
    focus: "Paid-tool access and fallback routing",
    primaryOutput: "strategy/TOOL_DECISIONS.md",
    order: 2,
    orientWindow: true,
  },
  {
    id: "phase.0c",
    key: "phase_0c",
    label: "0c",
    focus: "Secrets baseline",
    primaryOutput: "SECRETS.md, doppler.yaml, names-only .env.example",
    order: 3,
    orientWindow: true,
  },
  {
    id: "phase.1",
    key: "phase_1",
    label: "1",
    focus: "Research-backed spec",
    primaryOutput: "strategy/RESEARCH.md, LOCALIZATION_MARKET_RESEARCH.md, revised product/SPEC.md",
    order: 4,
  },
  {
    id: "phase.1b",
    key: "phase_1b",
    label: "1b",
    focus: "Analytics and attribution blueprint",
    primaryOutput: "analytics/ANALYTICS.md, analytics/analytics-plan.html",
    order: 5,
  },
  {
    id: "phase.1c",
    key: "phase_1c",
    label: "1c",
    focus: "11-star experience and product brainstorm",
    primaryOutput: "11_STAR_EXPERIENCE.md, 11-star-experience.html",
    order: 6,
  },
  { id: "phase.1d", key: "phase_1d", label: "1d", focus: "Paid user acquisition system", primaryOutput: "PAID_UA.md", order: 7 },
  { id: "phase.1e", key: "phase_1e", label: "1e", focus: "Viral growth loop contract", primaryOutput: "VIRAL_GROWTH.md, growth/LAUNCH_NARRATIVE.md", order: 8 },
  {
    id: "phase.1f",
    key: "phase_1f",
    label: "1f",
    focus: "Launch trace and build contracts",
    primaryOutput: "state/LAUNCH_TRACE.md, engineering/TECH_SPEC.md",
    order: 9,
  },
  { id: "phase.1g", key: "phase_1g", label: "1g", focus: "Security architecture", primaryOutput: "trust/SECURITY.md, trust/security-review.html", order: 10 },
  {
    id: "phase.2",
    key: "phase_2",
    label: "2",
    focus: "Brand and design",
    primaryOutput: "strategy/BRAND.md, design/DESIGN.md, design.md, rendered proofs, key assets",
    order: 11,
  },
  {
    id: "phase.3",
    key: "phase_3",
    label: "3",
    focus: "Launch dossier and store operations",
    primaryOutput: "Store listing, signing, console, screenshot, content-asset, and launch packets",
    order: 12,
  },
  {
    id: "phase.3b",
    key: "phase_3b",
    label: "3b",
    focus: "Revenue and monetization operations",
    primaryOutput: "revenue/REVENUE_OPS.md and sandbox/production purchase validation",
    order: 13,
  },
  {
    id: "phase.4",
    key: "phase_4",
    label: "4",
    focus: "Pre-launch funnel",
    primaryOutput: "Landing page, waitlist/referral loop, email/domain routes, analytics, deploy proof",
    order: 14,
  },
  {
    id: "phase.5",
    key: "phase_5",
    label: "5",
    focus: "Builder and agent handoff",
    primaryOutput: "AGENTS.md, CLAUDE.md, APP_AGENTS.md, agents/, PROMPTS.md, audit bundle",
    order: 15,
  },
  {
    id: "phase.5b",
    key: "phase_5b",
    label: "5b",
    focus: "Engineering orchestration and production readiness",
    primaryOutput: "engineering/ENGINEERING_PLAN.md, operations/ORCHESTRATION.md, engineering/PRODUCTION_READINESS.md, device proof",
    order: 16,
  },
  {
    id: "phase.5c",
    key: "phase_5c",
    label: "5c",
    focus: "Security release gate",
    primaryOutput: "Scan and review proof attached to engineering/PRODUCTION_READINESS.md",
    order: 17,
  },
  {
    id: "phase.6",
    key: "phase_6",
    label: "6",
    focus: "Post-launch UGC and Fastlane growth engine",
    primaryOutput: "growth/UGC_PLAYBOOK.md, growth/FASTLANE_OPS.md, 90-day format-discovery plan",
    order: 18,
  },
  {
    id: "phase.6b",
    key: "phase_6b",
    label: "6b",
    focus: "Post-launch operations",
    primaryOutput: "operations/POST_LAUNCH_OPS.md, operations/LAUNCH_RETRO.md, day-30 scope revisit",
    order: 19,
  },
] as const;
