import { workflow } from "./helpers.js";

export const workflows = [
  workflow({
    legacyId: "L27",
    id: "workflow.store.aso-and-store-ops",
    title: "ASO & store ops",
    domainId: "domain.store",
    areaIds: ["area.build-release"],
    trigger: "Before App Store/Play metadata, keyword research, ASA, or post-launch ASO loops",
    laneIds: ["lane.store-console"],
    phaseIds: ["phase.3"],
    upstreamWorkflowIds: ["workflow.design.design-room-state-mutate-version-render"],
    artifacts: ["STORE_OPS.md"],
    gates: ["check:aso-metadata"],
    operators: ["operator.engineering-leader", "operator.marketing-guru"],
  }),
  workflow({
    legacyId: "L28",
    id: "workflow.store.app-store-listing-prep-packet",
    title: "App Store listing prep packet",
    domainId: "domain.store",
    areaIds: ["area.build-release"],
    trigger: "Before listing fields, privacy questionnaire, IAP/subscription field maps, CPPs, in-app events",
    laneIds: ["lane.store-console"],
    phaseIds: ["phase.3"],
    upstreamWorkflowIds: ["workflow.store.aso-and-store-ops"],
    artifacts: ["app-store-listing/APP_STORE_LISTING.md"],
    gates: ["check:store-console"],
    operators: ["operator.engineering-leader", "operator.marketing-guru"],
  }),
  workflow({
    legacyId: "L29",
    id: "workflow.store.apple-signing-and-release-readiness",
    title: "Apple signing & release readiness",
    domainId: "domain.store",
    areaIds: ["area.build-release"],
    trigger: "Before Apple Developer enrollment, Team ID, signing, profiles, archive/upload, TestFlight",
    laneIds: ["lane.apple-signing"],
    phaseIds: ["phase.3"],
    upstreamWorkflowIds: ["workflow.store.app-store-listing-prep-packet"],
    artifacts: ["APPLE_SIGNING.md"],
    gates: ["check:apple-signing"],
    providers: ["provider.app-store-connect"],
    operators: ["operator.engineering-leader", "operator.marketing-guru"],
    founderOnlyActions: ["approve signing and submission"],
  }),
  workflow({
    legacyId: "L30",
    id: "workflow.store.apple-app-store-requirements-privacy-manifest",
    title: "Apple App Store requirements (privacy manifest)",
    domainId: "domain.store",
    areaIds: ["area.build-release"],
    trigger: "Before ASC upload — PrivacyInfo.xcprivacy, required-reason APIs, App Privacy answers",
    laneIds: ["lane.store-console", "lane.privacy-legal"],
    phaseIds: ["phase.3"],
    upstreamWorkflowIds: ["workflow.store.app-store-listing-prep-packet", "workflow.trust.privacy-and-terms"],
    artifacts: ["APPLE_APP_STORE_REQUIREMENTS.md"],
    gates: ["check:apple-requirements"],
    providers: ["provider.app-store-connect"],
    operators: ["operator.engineering-leader", "operator.marketing-guru"],
    founderOnlyActions: ["approve privacy answers"],
  }),
  workflow({
    legacyId: "L31",
    id: "workflow.store.store-console-workflow",
    title: "Store console workflow",
    domainId: "domain.store",
    areaIds: ["area.build-release"],
    trigger: 'Before "where do I click / what do I paste" in ASC or Play Console',
    laneIds: ["lane.store-console"],
    phaseIds: ["phase.3"],
    upstreamWorkflowIds: ["workflow.store.app-store-listing-prep-packet", "workflow.store.apple-signing-and-release-readiness"],
    artifacts: ["STORE_CONSOLE.md", "store-console.html"],
    gates: ["check:store-console"],
    providers: ["provider.app-store-connect", "provider.google-play"],
    operators: ["operator.engineering-leader", "operator.marketing-guru"],
    founderOnlyActions: ["approve external console mutations"],
  }),
  workflow({
    legacyId: "L32",
    id: "workflow.store.asc-cli-automation",
    title: "ASC CLI automation",
    domainId: "domain.store",
    areaIds: ["area.build-release"],
    trigger: "Before Rork asc CLI app creation, metadata, screenshots, TestFlight, RevenueCat sync",
    laneIds: ["lane.store-console"],
    phaseIds: ["phase.3"],
    upstreamWorkflowIds: ["workflow.store.store-console-workflow"],
    artifacts: ["STORE_CONSOLE.md"],
    gates: ["check:asc-command-contract"],
    providers: ["provider.app-store-connect"],
    operators: ["operator.engineering-leader", "operator.marketing-guru"],
    founderOnlyActions: ["approve App Store Connect mutations"],
  }),
  workflow({
    legacyId: "L33",
    id: "workflow.store.store-screenshots-production",
    title: "Store screenshots production",
    domainId: "domain.store",
    areaIds: ["area.build-release"],
    trigger: "Store screenshots needed (raw capture → composed iPhone/iPad/Play assets)",
    laneIds: ["lane.store-console", "lane.content-assets"],
    phaseIds: ["phase.3"],
    upstreamWorkflowIds: ["workflow.design.design-room-state-mutate-version-render", "workflow.store.app-store-listing-prep-packet"],
    artifacts: ["app-store-listing/SCREENSHOTS.md"],
    gates: ["check:store-screenshots"],
    providers: ["provider.app-store-screenshots"],
    operators: ["operator.engineering-leader", "operator.marketing-guru"],
  }),
  workflow({
    legacyId: "L34",
    id: "workflow.store.google-play-release",
    title: "Google Play release",
    domainId: "domain.store",
    areaIds: ["area.build-release"],
    trigger: "Android in scope (platforms include android or an android bundle id exists)",
    laneIds: ["lane.store-console"],
    phaseIds: ["phase.3"],
    upstreamWorkflowIds: ["workflow.store.app-store-listing-prep-packet"],
    artifacts: ["GOOGLE_PLAY_RELEASE.md"],
    gates: ["check:google-play"],
    providers: ["provider.google-play"],
    operators: ["operator.engineering-leader", "operator.marketing-guru"],
    founderOnlyActions: ["approve Play Console release"],
  }),
  workflow({
    legacyId: "L35",
    id: "workflow.engineering.engineering-orchestration-ce-production-readiness",
    title: "Engineering orchestration (CE + production readiness)",
    domainId: "domain.engineering",
    areaIds: ["area.build-release"],
    trigger: "Before actual app implementation, builder prompts, or production-readiness claims",
    laneIds: ["lane.engineering", "lane.orchestration"],
    phaseIds: ["phase.5b"],
    upstreamWorkflowIds: ["workflow.process.launch-trace-and-build-contracts", "workflow.design.design-room-state-mutate-version-render"],
    artifacts: ["ENGINEERING_PLAN.md", "ORCHESTRATION.md", "PRODUCTION_READINESS.md"],
    gates: ["check:compound-engineering", "check:orchestration"],
    operators: ["operator.engineering-leader", "operator.security-architect"],
  }),
  workflow({
    legacyId: "L36",
    id: "workflow.engineering.backend-data-contract",
    title: "Backend data contract",
    domainId: "domain.engineering",
    areaIds: ["area.build-release"],
    trigger: "Before schema/auth prompts or TECH_SPEC.md data/API sections harden",
    laneIds: ["lane.engineering"],
    phaseIds: ["phase.1f", "phase.5b"],
    upstreamWorkflowIds: ["workflow.process.launch-trace-and-build-contracts"],
    artifacts: ["TECH_SPEC.md"],
    gates: ["check:backend-contract"],
    operators: ["operator.engineering-leader", "operator.security-architect"],
  }),
  workflow({
    legacyId: "L37",
    id: "workflow.engineering.app-agent-roster-and-repo-entrypoints",
    title: "App agent roster & repo entrypoints",
    domainId: "domain.engineering",
    areaIds: ["area.build-release"],
    trigger: "Before builder handoff bundles, AGENTS.md/CLAUDE.md, APP_AGENTS.md, agents/",
    laneIds: ["lane.engineering"],
    phaseIds: ["phase.5"],
    upstreamWorkflowIds: ["workflow.engineering.engineering-orchestration-ce-production-readiness"],
    artifacts: ["AGENTS.md", "CLAUDE.md", "APP_AGENTS.md"],
    gates: ["check:agent-entrypoints"],
    operators: ["operator.engineering-leader", "operator.security-architect"],
  }),
  workflow({
    legacyId: "L38",
    id: "workflow.engineering.mobai-device-automation-and-demo-videos",
    title: "MobAI device automation & demo videos",
    domainId: "domain.engineering",
    areaIds: ["area.build-release"],
    trigger: "Before device automation, app-flow demo videos, app previews, bug-repro recordings",
    laneIds: ["lane.engineering", "lane.content-assets"],
    phaseIds: ["phase.5b"],
    upstreamWorkflowIds: ["workflow.engineering.engineering-orchestration-ce-production-readiness"],
    artifacts: ["DEMO_VIDEO.md", "PRODUCTION_READINESS.md"],
    gates: ["check:mobai-proof"],
    providers: ["provider.mobai"],
    operators: ["operator.engineering-leader", "operator.security-architect"],
  }),
  workflow({
    legacyId: "L39",
    id: "workflow.engineering.native-ios-proof-route-ladder",
    title: "Native iOS proof (Route Ladder)",
    domainId: "domain.engineering",
    areaIds: ["area.build-release"],
    trigger: "Before in-app iOS Simulator / Codex Desktop native iOS / XcodeBuildMCP / serve-sim / SnapshotPreviews proof",
    laneIds: ["lane.engineering"],
    phaseIds: ["phase.5b"],
    upstreamWorkflowIds: ["workflow.engineering.engineering-orchestration-ce-production-readiness"],
    artifacts: ["PRODUCTION_READINESS.md"],
    gates: ["check:native-ios"],
    providers: ["provider.in-app-ios-simulator", "provider.codex-native-ios", "provider.snapshot-previews", "provider.serve-sim"],
    operators: ["operator.engineering-leader", "operator.security-architect"],
  }),
] as const;
