import { workflow } from "./helpers.js";

export const workflows = [
  workflow({
    id: "workflow.data.analytics-and-attribution-blueprint",
    title: "Analytics & attribution blueprint",
    domainId: "domain.data",
    areaIds: ["area.growth-revenue"],
    trigger: "Before locking onboarding/paywall/funnels/store CTAs or any prompt naming events",
    laneIds: ["lane.analytics-attribution"],
    phaseIds: ["phase.1b"],
    dependencies: ["workflow.research.research-backed-spec"],
    outputPaths: ["ANALYTICS.md", "analytics-plan.html"],
    gates: ["check:analytics-catalog", "check:attribution"],
    providers: ["provider.posthog"],
    operators: ["operator.product-leader", "operator.marketing-guru"],
  }),
  workflow({
    id: "workflow.growth.paid-user-acquisition-system",
    title: "Paid user-acquisition system",
    domainId: "domain.growth",
    areaIds: ["area.growth-revenue"],
    trigger: "Before paid ads, ASA, Meta/TikTok/Google campaigns, or spend-readiness claims",
    laneIds: ["lane.paid-user-acquisition"],
    phaseIds: ["phase.1d"],
    dependencies: ["workflow.data.analytics-and-attribution-blueprint"],
    outputPaths: ["growth/PAID_UA.md"],
    gates: ["check:paid-ua"],
    providers: ["provider.paid-ad-channels", "provider.posthog", "provider.revenuecat"],
    operators: ["operator.marketing-guru"],
    founderOnlyActions: ["approve ad-account access and spend"],
  }),
  workflow({
    id: "workflow.growth.viral-growth-loop",
    title: "Viral growth loop",
    domainId: "domain.growth",
    areaIds: ["area.growth-revenue"],
    trigger: "Before referral/share-to-unlock/invite/comment-loop mechanics",
    laneIds: ["lane.growth"],
    phaseIds: ["phase.1e"],
    dependencies: ["workflow.data.analytics-and-attribution-blueprint"],
    outputPaths: ["growth/VIRAL_GROWTH.md"],
    gates: ["check:viral-growth"],
    operators: ["operator.marketing-guru"],
  }),
  workflow({
    id: "workflow.growth.launch-narrative-and-cadence",
    title: "Launch narrative & cadence",
    domainId: "domain.growth",
    areaIds: ["area.growth-revenue"],
    trigger: "Before the public announcement, launch-day run-of-show, or weekly release rhythm",
    laneIds: ["lane.growth"],
    phaseIds: ["phase.1e", "phase.3", "phase.6"],
    dependencies: ["workflow.data.analytics-and-attribution-blueprint", "workflow.growth.viral-growth-loop"],
    outputPaths: ["growth/LAUNCH_NARRATIVE.md"],
    gates: ["check:launch-narrative"],
    operators: ["operator.marketing-guru"],
    founderOnlyActions: ["approve public launch posting"],
  }),
  workflow({
    id: "workflow.money.revenue-monetization",
    title: "Revenue monetization",
    domainId: "domain.money",
    areaIds: ["area.growth-revenue"],
    trigger: "Before RevenueCat/Stripe/web billing, products, paywall, entitlement, webhooks, pricing",
    laneIds: ["lane.revenue"],
    phaseIds: ["phase.3b"],
    dependencies: ["workflow.process.launch-trace-and-build-contracts"],
    outputPaths: ["REVENUE_OPS.md"],
    gates: ["check:revenue"],
    providers: ["provider.revenuecat", "provider.stripe"],
    operators: ["operator.engineering-leader", "operator.marketing-guru"],
    founderOnlyActions: ["approve pricing and product catalog"],
  }),
  workflow({
    id: "workflow.growth.geo-seo-public-visibility",
    title: "GEO/SEO public visibility",
    domainId: "domain.growth",
    areaIds: ["area.growth-revenue"],
    trigger: "Before editing any landing/policy/blog copy, robots.txt, llms.txt, sitemap, schema, metadata",
    laneIds: ["lane.growth"],
    phaseIds: ["phase.4"],
    dependencies: ["workflow.process.launch-trace-and-build-contracts"],
    outputPaths: ["GEO_SEO.md"],
    gates: ["check:landing-funnel"],
    operators: ["operator.marketing-guru"],
  }),
  workflow({
    id: "workflow.growth.pre-launch-funnel-landing-waitlist",
    title: "Pre-launch funnel (landing/waitlist)",
    domainId: "domain.growth",
    areaIds: ["area.growth-revenue"],
    trigger: "Phase 4 — landing page, waitlist/referral loop, web funnel, live deploy verification",
    laneIds: ["lane.growth"],
    phaseIds: ["phase.4"],
    dependencies: ["workflow.growth.geo-seo-public-visibility"],
    outputPaths: ["landing/"],
    gates: ["check:landing-funnel"],
    operators: ["operator.marketing-guru"],
  }),
  workflow({
    id: "workflow.growth.ugc-creator-engine",
    title: "UGC creator engine",
    domainId: "domain.growth",
    areaIds: ["area.growth-revenue"],
    trigger: "Before founder-led organic social, creator sourcing/contracts, format-discovery tests",
    laneIds: ["lane.growth"],
    phaseIds: ["phase.6"],
    dependencies: ["workflow.growth.viral-growth-loop", "workflow.growth.launch-narrative-and-cadence"],
    outputPaths: ["UGC_PLAYBOOK.md"],
    gates: ["check:viral-growth"],
    operators: ["operator.marketing-guru"],
  }),
  workflow({
    id: "workflow.growth.fastlane-growth-ops",
    title: "Fastlane growth ops",
    domainId: "domain.growth",
    areaIds: ["area.growth-revenue"],
    trigger: "After launch approval/public beta, or usefastlane.ai/Blitz setup, scheduling, social analytics",
    laneIds: ["lane.growth", "lane.post-launch-ops"],
    phaseIds: ["phase.6"],
    dependencies: ["workflow.growth.launch-narrative-and-cadence"],
    outputPaths: ["FASTLANE_OPS.md"],
    gates: ["check:post-launch"],
    operators: ["operator.marketing-guru"],
    founderOnlyActions: ["approve social connections and scheduled posts"],
  }),
] as const;
