import { workflow } from "./helpers.js";

export const workflows = [
  workflow({
    legacyId: "L01",
    id: "workflow.machine.runtime-freshness-gate-consumer-side",
    title: "Runtime freshness gate (consumer side)",
    domainId: "domain.machine",
    areaIds: ["area.skill-maintenance"],
    trigger: "Before substantial launch/design/store/revenue/build work when the installed runtime may be behind source",
    artifacts: ["skill-version.json"],
    gates: ["check:skill-version"],
    operators: ["operator.maintainer", "operator.validator"],
  }),
  workflow({
    legacyId: "L48",
    id: "workflow.machine.source-freshness-maintenance-maintainer",
    title: "Source-freshness maintenance (maintainer)",
    domainId: "domain.machine",
    areaIds: ["area.skill-maintenance"],
    trigger: "Maintaining the skill, adding external URLs, refreshing third-party docs/commands",
    artifacts: ["machine/source-registry.yaml"],
    gates: ["check:source-registry"],
    operators: ["operator.maintainer", "operator.validator"],
  }),
  workflow({
    legacyId: "L50",
    id: "workflow.machine.skill-runtime-sync-and-version-discipline-maintainer",
    title: "Skill runtime sync & version discipline (maintainer)",
    domainId: "domain.machine",
    areaIds: ["area.skill-maintenance"],
    trigger: "After any skill change — bump version, sync the installed runtime, run the readiness gate",
    upstreamWorkflowIds: ["workflow.machine.source-freshness-maintenance-maintainer"],
    artifacts: ["skill-version.json"],
    gates: ["check:version-discipline", "check:skill-version"],
    operators: ["operator.maintainer", "operator.validator"],
  }),
  workflow({
    legacyId: "L54",
    id: "workflow.machine.founder-language-translation-maintainer",
    title: "Founder-language translation (maintainer)",
    domainId: "domain.machine",
    areaIds: ["area.skill-maintenance"],
    trigger: "Adding or renaming a lane, status, phase, autonomy mode, or provider route; any founder-visible surface change",
    laneIds: [],
    upstreamWorkflowIds: ["workflow.words.writing-quality-no-slop"],
    artifacts: ["scripts/lib/founder-copy.ts"],
    gates: ["check:founder-copy"],
    operators: ["operator.maintainer", "operator.validator"],
  }),
  workflow({
    legacyId: "L55",
    id: "workflow.machine.skill-triggering-contract-maintainer",
    title: "Skill triggering contract (maintainer)",
    domainId: "domain.machine",
    areaIds: ["area.skill-maintenance"],
    trigger: "Changing SKILL.md frontmatter, the skill description, or the trigger phrasing",
    laneIds: [],
    artifacts: ["SKILL.md"],
    gates: ["check:autopilot"],
    operators: ["operator.maintainer", "operator.validator"],
  }),
  workflow({
    legacyId: "L56",
    id: "workflow.machine.asc-command-contract-maintainer",
    title: "ASC command contract (maintainer)",
    domainId: "domain.machine",
    areaIds: ["area.skill-maintenance"],
    trigger: "Before changing any documented asc command in playbook/store/app-store-connect-cli.md",
    laneIds: ["lane.store-console"],
    upstreamWorkflowIds: ["workflow.store.asc-cli-automation"],
    artifacts: ["playbook/store/app-store-connect-cli.md"],
    gates: ["check:asc-command-contract"],
    operators: ["operator.maintainer", "operator.validator"],
  }),

  workflow({
    legacyId: "L57",
    id: "workflow.machine.definition-graph-maintenance",
    title: "Definition graph maintenance",
    domainId: "domain.machine",
    areaIds: ["area.skill-maintenance"],
    trigger: "Changing a domain, workflow, context pack, phase, lane, operator, provider, artifact, gate, or generated graph projection",
    artifacts: ["graph/generated/skill-graph.json", "graph/generated/skill-graph.md", "graph/generated/context-report.json"],
    gates: ["check:skill-graph", "render:skill-graph"],
    operators: ["operator.maintainer", "operator.validator", "operator.renderer"],
  }),
] as const;
