import { workflow } from "./helpers.js";

export const workflows = [
  workflow({
    id: "workflow.operations.paid-tool-routing-and-fallback",
    title: "Paid-tool routing & fallback",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before using or replacing any paid/account-gated tool, or before a free fallback",
    laneIds: ["lane.paid-tool-routing"],
    phaseIds: ["phase.0b"],
    outputPaths: ["strategy/TOOL_DECISIONS.md"],
    gates: ["check:paid-tool-decisions"],
    providers: ["provider.doppler"],
    operators: ["operator.orchestrator", "operator.customer-success"],
    founderOnlyActions: ["approve a paid or constrained fallback"],
  }),
  workflow({
    id: "workflow.operations.secrets-baseline-and-routing",
    title: "Secrets baseline & routing",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before any new secret, key, token, env var, webhook secret, or .env",
    laneIds: ["lane.secrets"],
    phaseIds: ["phase.0c"],
    outputPaths: ["trust/secrets/SECRETS.md"],
    gates: ["check:secrets"],
    providers: ["provider.doppler"],
    operators: ["operator.orchestrator", "operator.customer-success"],
    founderOnlyActions: ["provide or authorize credentials"],
  }),
  workflow({
    id: "workflow.trust.security-architecture-and-release-gate",
    title: "Security architecture & release gate",
    domainId: "domain.trust",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before threat modeling, hardening, scans, or any security-readiness claim",
    laneIds: ["lane.security"],
    phaseIds: ["phase.1g", "phase.5c"],
    outputPaths: ["trust/SECURITY.md", "trust/security-review.html"],
    gates: ["check:security"],
    providers: ["provider.security-review", "provider.sentry"],
    operators: ["operator.security-architect"],
    founderOnlyActions: ["accept residual security risk"],
  }),
  workflow({
    id: "workflow.trust.privacy-and-terms",
    title: "Privacy & terms",
    domainId: "domain.trust",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before privacy policy, terms, EULA, subscription terms, account-deletion, store disclosures",
    laneIds: ["lane.privacy-legal"],
    phaseIds: ["phase.3"],
    dependencies: ["workflow.process.launch-trace-and-build-contracts"],
    outputPaths: ["trust/PRIVACY.md", "trust/TERMS.md", "LEGAL_REVIEW.md"],
    gates: ["check:privacy-terms"],
    operators: ["operator.security-architect"],
    founderOnlyActions: ["approve legal text"],
  }),
  workflow({
    id: "workflow.operations.resend-email-ops",
    title: "Resend email ops",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before Resend domains/keys, transactional/lifecycle/broadcast email, deliverability",
    laneIds: ["lane.email"],
    phaseIds: ["phase.4", "phase.6"],
    dependencies: ["workflow.design.design-room-state-mutate-version-render", "workflow.data.analytics-and-attribution-blueprint"],
    outputPaths: ["growth/EMAIL_OPS.md"],
    gates: ["check:email"],
    providers: ["provider.resend"],
    operators: ["operator.orchestrator", "operator.customer-success"],
  }),
  workflow({
    id: "workflow.operations.post-launch-operations",
    title: "Post-launch operations",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: 'App live (phase_6/6b), "what now", weekly ops, incident response, retention reviews',
    laneIds: ["lane.post-launch-ops"],
    phaseIds: ["phase.6b"],
    dependencies: ["workflow.engineering.engineering-orchestration-ce-production-readiness"],
    outputPaths: ["operations/POST_LAUNCH_OPS.md", "operations/LAUNCH_RETRO.md"],
    gates: ["check:post-launch"],
    operators: ["operator.orchestrator", "operator.customer-success"],
    founderOnlyActions: ["decide Kill, Hold, Fix, or Scale"],
  }),
  workflow({
    id: "workflow.operations.founder-zero-operator-bootstrap",
    title: "Founder-zero operator bootstrap",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Every broad launch start; before account/social/Doppler bootstrap; when an agent is about to hand back a checklist",
    laneIds: [],
    outputPaths: ["operations/BUSINESS_ACCESS.md", "operations/business-access.json"],
    gates: ["check:founder-operator"],
    operators: ["operator.orchestrator", "operator.customer-success"],
    founderOnlyActions: ["provide account ownership decisions"],
  }),
  workflow({
    id: "workflow.operations.agent-operations-ledger",
    title: "Agent operations ledger",
    domainId: "domain.operations",
    areaIds: ["area.business-operations-trust"],
    trigger: "Before any authenticated browser/API/CLI/native action on a provider, social, or store account",
    laneIds: [],
    outputPaths: ["operations/AGENT_OPERATIONS.md", "operations/agent-operations.json"],
    gates: ["check:agent-operations"],
    providers: ["provider.app-store-connect", "provider.google-play", "provider.posthog", "provider.revenuecat"],
    operators: ["operator.orchestrator", "operator.customer-success"],
    founderOnlyActions: ["approve exact authenticated actions"],
  }),
] as const;
