import { workflow } from "./helpers.js";

export const workflows = [
  workflow({
    id: "workflow.orchestration.session-continuity-resume",
    title: "Session continuity / resume",
    domainId: "domain.orchestration",
    areaIds: ["area.operating-system"],
    trigger: "New session, resume, status check, or handoff on an existing launch",
    laneIds: ["lane.orchestration"],
    outputPaths: ["PROJECT_STATE.yaml", "launch-cockpit.html"],
    gates: ["check:continuity-contract"],
    operators: ["operator.orchestrator"],
  }),
  workflow({
    id: "workflow.orchestration.orient-scaffold-and-state-cockpit-upkeep",
    title: "Orient, scaffold & state/cockpit upkeep",
    domainId: "domain.orchestration",
    areaIds: ["area.operating-system"],
    trigger: '"Launch this app" / broad launch request; any lane/provider/proof/blocker status change',
    laneIds: ["lane.orchestration"],
    phaseIds: ["phase.0-orient"],
    outputPaths: ["PROJECT_STATE.yaml", "launch-cockpit.html", "BUSINESS_ACCESS.md"],
    gates: ["validate:launch-state", "render:launch-cockpit"],
    operators: ["operator.orchestrator"],
  }),
  workflow({
    id: "workflow.process.provider-proof-verification",
    title: "Provider-proof verification",
    domainId: "domain.process",
    areaIds: ["area.operating-system"],
    trigger: "Before marking any provider-backed lane (analytics/revenue/email/store/security/eng) done",
    laneIds: [],
    outputPaths: ["PROVIDER_PROOF.md"],
    gates: ["check:provider-proof"],
    providers: ["provider.posthog", "provider.revenuecat", "provider.resend", "provider.app-store-connect"],
    operators: ["operator.orchestrator", "operator.validator"],
  }),
  workflow({
    id: "workflow.process.change-cascade",
    title: "Change cascade",
    domainId: "domain.process",
    areaIds: ["area.operating-system"],
    trigger: "Any change to a launched/near-launch app's feature, copy, brand, pricing, products, or data behavior",
    laneIds: [],
    outputPaths: ["PROJECT_STATE.yaml", "LAUNCH_TRACE.md"],
    gates: ["check:change-cascade"],
    operators: ["operator.orchestrator", "operator.validator"],
  }),
  workflow({
    id: "workflow.process.launch-trace-and-build-contracts",
    title: "Launch trace & build contracts",
    domainId: "domain.process",
    areaIds: ["area.operating-system"],
    trigger: "Crossing research → product/design/build; deciding if TECH_SPEC.md is needed",
    laneIds: ["lane.traceability"],
    phaseIds: ["phase.1f"],
    dependencies: ["workflow.research.research-backed-spec", "workflow.experience.11-star-experience"],
    outputPaths: ["LAUNCH_TRACE.md", "TECH_SPEC.md"],
    gates: ["check:launch-trace"],
    operators: ["operator.orchestrator", "operator.validator"],
  }),
  workflow({
    id: "workflow.process.business-control-plane-extension",
    title: "Business Control Plane extension",
    domainId: "domain.process",
    areaIds: ["area.operating-system"],
    trigger: "Extending the Design Room into new analytics/monetization/store/growth panels over the same state",
    laneIds: [],
    outputPaths: ["state/workspace.generated.json"],
    gates: ["check:control-plane", "check:business-control-plane-workspace"],
    operators: ["operator.orchestrator", "operator.validator"],
  }),
  workflow({
    id: "workflow.process.launchbench-failure-cards-coverage-audit",
    title: "LaunchBench / failure-cards / coverage audit",
    domainId: "domain.process",
    areaIds: ["area.operating-system"],
    trigger: "Before any launch-readiness claim, after a repeated miss, or adding a validator/scenario",
    laneIds: [],
    dependencies: ["workflow.orchestration.orient-scaffold-and-state-cockpit-upkeep"],
    outputPaths: ["FAILURE_CARDS.md", "LAUNCHBENCH.md"],
    gates: ["launchbench", "check:lane-coverage"],
    operators: ["operator.orchestrator", "operator.validator"],
  }),
] as const;
