import { workflow } from "./helpers.js";

export const workflows = [
  workflow({
    legacyId: "L06",
    id: "workflow.product.app-archetype-detection-and-starter",
    title: "App-archetype detection & starter",
    domainId: "domain.product",
    areaIds: ["area.product-experience"],
    trigger: "Request matches a known product shape (social / AI-chat / habit / photo-AI)",
    laneIds: ["lane.product"],
    artifacts: ["SPEC.md"],
    gates: ["check:app-archetype", "check:archetype-starter"],
    operators: ["operator.product-leader"],
  }),
  workflow({
    legacyId: "L09",
    id: "workflow.research.research-backed-spec",
    title: "Research-backed spec",
    domainId: "domain.research",
    areaIds: ["area.product-experience"],
    trigger: "Need category economics, competitor, review/social-language, keyword, or name-collision evidence",
    laneIds: ["lane.research", "lane.product"],
    phaseIds: ["phase.1"],
    artifacts: ["RESEARCH.md", "SPEC.md"],
    gates: ["check:research", "check:product-spec"],
    operators: ["operator.product-leader"],
    founderOnlyActions: ["decide Go, Pivot, or Kill"],
  }),
  workflow({
    legacyId: "L10",
    id: "workflow.research.localization-market-research",
    title: "Localization market research",
    domainId: "domain.research",
    areaIds: ["area.product-experience"],
    trigger: "Before localizing any surface or choosing locales",
    laneIds: ["lane.research"],
    phaseIds: ["phase.1"],
    artifacts: ["localization-market-research/LOCALIZATION_MARKET_RESEARCH.md"],
    gates: ["check:localization-research"],
    providers: ["provider.aso-skills"],
    operators: ["operator.product-leader"],
  }),
  workflow({
    legacyId: "L12",
    id: "workflow.experience.11-star-experience",
    title: "11-star experience",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: '"11-star run" / before SPEC, onboarding, ads, store creative, or eng plans harden',
    laneIds: ["lane.experience"],
    phaseIds: ["phase.1c"],
    upstreamWorkflowIds: ["workflow.research.research-backed-spec"],
    artifacts: ["11-star-experience/11_STAR_EXPERIENCE.md", "11-star-experience/11-star-experience.html"],
    gates: ["check:11-star"],
    operators: ["operator.product-leader", "operator.design-guru"],
  }),
  workflow({
    legacyId: "L13",
    id: "workflow.experience.emotional-experience-design-producer",
    title: "Emotional experience design (producer)",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: 'Feature whose 11-star target is 6★+ / "charge this with emotion", "build a habit"',
    laneIds: ["lane.emotional-design"],
    phaseIds: ["phase.1c"],
    upstreamWorkflowIds: ["workflow.experience.11-star-experience", "workflow.data.analytics-and-attribution-blueprint"],
    artifacts: ["emotional-design/EMOTIONAL_DESIGN.md"],
    gates: ["check:emotional-design"],
    operators: ["operator.product-leader", "operator.design-guru"],
  }),
  workflow({
    legacyId: "L14",
    id: "workflow.experience.emotional-design-audit-auditor",
    title: "Emotional design audit (auditor)",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: '"Audit this app\'s emotional design" / "emotional UX audit"',
    laneIds: ["lane.emotional-design"],
    phaseIds: ["phase.1c"],
    upstreamWorkflowIds: ["workflow.experience.emotional-experience-design-producer"],
    artifacts: ["emotional-design/EMOTIONAL_AUDIT.md"],
    gates: ["check:emotional-design"],
    operators: ["operator.product-leader", "operator.design-guru"],
  }),
  workflow({
    legacyId: "L20",
    id: "workflow.design.design-room-state-mutate-version-render",
    title: "Design Room (state→mutate→version→render)",
    domainId: "domain.design",
    areaIds: ["area.product-experience"],
    trigger: "Any design/visual-system/cross-surface/store-creative/landing/onboarding/paywall work",
    laneIds: ["lane.design"],
    phaseIds: ["phase.2"],
    upstreamWorkflowIds: ["workflow.process.launch-trace-and-build-contracts"],
    artifacts: ["state/business.json", "state/theme.tokens.json", "design-room.html"],
    gates: ["validate:design-state", "check:design-room", "render:design-room"],
    operators: ["operator.design-guru"],
    founderOnlyActions: ["approve final brand direction"],
  }),
  workflow({
    legacyId: "L21",
    id: "workflow.design.token-promotion",
    title: "Token promotion",
    domainId: "domain.design",
    areaIds: ["area.product-experience"],
    trigger: "Theme tokens change and the design is accepted",
    laneIds: ["lane.design"],
    phaseIds: ["phase.2"],
    upstreamWorkflowIds: ["workflow.design.design-room-state-mutate-version-render"],
    artifacts: ["design-system/tokens.json", "design-system/tokens.css", "design-system/DesignTokens.swift"],
    gates: ["check:token-promotion"],
    operators: ["operator.design-guru"],
  }),
  workflow({
    legacyId: "L22",
    id: "workflow.design.ux-patterns-refero",
    title: "UX patterns (Refero)",
    domainId: "domain.design",
    areaIds: ["area.product-experience"],
    trigger: "Before flow maps, state matrices, UX_PATTERNS.md, or bug-trap coverage",
    laneIds: ["lane.design"],
    phaseIds: ["phase.2"],
    upstreamWorkflowIds: ["workflow.design.design-room-state-mutate-version-render"],
    artifacts: ["ux-patterns/UX_PATTERNS.md"],
    gates: ["check:ux-patterns"],
    providers: ["provider.refero"],
    operators: ["operator.design-guru"],
  }),
  workflow({
    legacyId: "L23",
    id: "workflow.experience.onboarding-conversion",
    title: "Onboarding conversion",
    domainId: "domain.experience",
    areaIds: ["area.product-experience"],
    trigger: "Before onboarding quizzes, review-prompt timing, paywall timing, or first-session activation",
    laneIds: ["lane.onboarding"],
    phaseIds: ["phase.1c", "phase.2"],
    upstreamWorkflowIds: ["workflow.data.analytics-and-attribution-blueprint", "workflow.experience.11-star-experience"],
    artifacts: ["ONBOARDING.md", "onboarding.html"],
    gates: ["check:onboarding"],
    operators: ["operator.product-leader", "operator.design-guru"],
  }),
  workflow({
    legacyId: "L24",
    id: "workflow.design.premium-mobile-craft",
    title: "Premium mobile craft",
    domainId: "domain.design",
    areaIds: ["area.product-experience"],
    trigger: 'Before in-app UI build/polish, press-state/haptics/loading-empty wiring, or "premium feel"',
    laneIds: ["lane.design"],
    artifacts: ["DESIGN.md", "ux-patterns/UX_PATTERNS.md"],
    gates: ["check:ux-patterns", "check:motion-contract"],
    operators: ["operator.design-guru"],
  }),
  workflow({
    legacyId: "L25",
    id: "workflow.design.content-assets-remotion-generated-visuals",
    title: "Content assets / Remotion / generated visuals",
    domainId: "domain.design",
    areaIds: ["area.product-experience"],
    trigger: "Before rendered videos/stills, app previews, ad/social variants",
    laneIds: ["lane.content-assets"],
    phaseIds: ["phase.2", "phase.3"],
    upstreamWorkflowIds: ["workflow.design.design-room-state-mutate-version-render"],
    artifacts: ["content-assets/CONTENT_ASSETS.md", "content-assets/content-assets.html"],
    gates: ["check:content-assets"],
    providers: ["provider.higgsfield"],
    operators: ["operator.design-guru"],
  }),
  workflow({
    legacyId: "L53",
    id: "workflow.words.writing-quality-no-slop",
    title: "Writing quality (no-slop)",
    domainId: "domain.words",
    areaIds: ["area.product-experience"],
    trigger: "Before writing or reviewing any founder-facing copy or any marketing copy the skill generates",
    laneIds: [],
    artifacts: ["COPY_BRIEF.md", "COPY_DECK.md"],
    gates: ["check:no-slop", "check:app-copy"],
    operators: ["operator.marketing-guru", "operator.customer-success"],
  }),
] as const;
